### ISSUE TITLE
Précision requête n°4 "minicampus" (monotable) 

### ISSUE THREAD

**Issue by Mathieu-R** [EPHEC-TI/2TI#2]
Pour la requète répondant à la question suivante : 

`Afficher les filles d'une section donnée (p.e. TI)`

Ne serait-il pas mieux de faire :
```sql
select nom
from class
where parent_id = (
	select id
    from class
    where nom = 'TI'
)
```
@KeydownR

**Comment by chrisvanberg** [comment]
En effet c'est plus propre =) Je vais modifier ça
