### ISSUE TITLE
Lab06 S1-RT-01 OSPF G0/0 is Passive-Interface

### ISSUE THREAD

**Issue by Julien00859** [EPHEC-TI/2TI#4]
As S1-CSW-01 and S1-CSW-02 are ospf router, they need to communicate with S1-RT-01
However the interface on which the router (S1-RT-01) could receive those infos is set as passive-interface

Blame: https://github.com/EPHEC-TI/2TI/commit/e3360d598309004c8f4f5bf7de4ff60b8adf2e97

**Comment by izanagi1995** [comment]
LGTM
