### ISSUE TITLE
2TI/201-DevAvancéApp/2-Pratique has a complete repository ready to be pushed

### ISSUE THREAD

**Issue by melvinmajor** [EPHEC-TI/2TI#5]
I have a complete repository of all what has been done for the practice Lesson of Java but unfortunately, I can't push anything here because :
`Uploads are disabled.
File uploads require push access to this repository.`

I'm in 2TI so, I can push everything if I'm set as a contributor of this repository ;-)

Everything is there :
https://github.com/melvinmajor/T2012-Java_EPHEC

**Comment by NicoleEtLui** [comment]
Hi, 

 I don’t personally have the abality to grant you push access to the repo but you can ask keydownR (https://github.com/KeydownR?tab=overview&from=2017-12-01&to=2017-12-31) or Izanagi (https://github.com/izanagi1995?tab=overview&from=2018-05-01&to=2018-05-31).

Or you can just od a pull request I’ll accept it asap !

**Comment by izanagi1995** [comment]
@melvinmajor I sent you an invite with access to 1TI 2TI and 3TI. Thanks and have a great day!
